anfibackend/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('infoAnfibio/',include('infoAnfibio.urls'))
]

infoAnfibio/urls.py
from . import views
from django.urls import path

app_name='infoAnfibio'

urlpatterns = [
    path('infoUsuarios',views.infoUsuarios,name='infoUsuarios'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('accederUsuario',views.accederUsuario,name='accederUsuario'),
    path('datosUsuario',views.datosUsuario,name='datosUsuario'),
    path('infoBoats',views.infoBoats,name='infoBoats'),
    path('infoFotos',views.infoFotos,name='infoFotos'),
    path('consultarEstadisticas',views.consultarEstadisticas,name='consultarEstadisticas'),
    path('infoInspecciones',views.infoInspecciones,name='infoInspecciones'),
    path('registrarTrabajo',views.registrarTrabajo,name='registrarTrabajo'),
    path('foto/<str:ind>',views.foto,name='foto'),
    path('capturarFoto',views.capturarFoto,name='capturarFoto'),
    path('fotosInspeccionTotal',views.fotosInspeccionTotal,name='fotosInspeccionTotal'),
    path('videosInspeccionTotal',views.videosInspeccionTotal,name='videosInspeccionTotal'),
    path('verVideos',views.verVideos,name='verVideos'),
    path('comandoInfo',views.comandoInfo,name='comandoInfo'),
    path('iniciarInspeccion',views.iniciarInspeccion,name='iniciarInspeccion'),
    path('capturarFotoInspeccion',views.capturarFotoInspeccion,name='capturarFotoInspeccion'),
    path('fotosInspeccionEspecifico/<str:ind>',views.fotosInspeccionEspecifico,name='fotosInspeccionEspecifico'),
    path('encenderLucesFL',views.encendeLucesFL,name='encenderLucesFL'),
    path('apagarLucesFL',views.apagarLucesFL,name='apagarLucesFL'),
    path('encenderLucesBL',views.encenderLucesBL,name='encenderLucesBL'),
    path('apagarLucesBL',views.apagarLucesBL,name='apagarLucesBL'),
    path('encenderLucesLV',views.encenderLucesLV,name='encenderLucesLV'),
    path('apagarLucesLV',views.apagarLucesLV,name='apagarLucesLV'),
    path('grabar_video_inspeccion_anfibio',views.grabar_video_inspeccion_anfibio,name='grabar_video_inspeccion_anfibio'),
    path('detener_video_inspeccion_anfibio',views.detener_video_inspeccion_anfibio,name='detener_video_inspeccion_anfibio'),
    path('videoPlayer/<str:ind>',views.videoPlayer,name='videoPlayer'),
    path('videosInspeccionEspecifico/<str:ind>',views.videosInpeccionEspecifico,name='videosInspeccionEspecifico'),
    path('videoEspecifico/<str:ind>/<str:info>',views.videoEspecifico,name='videoEspecifico')
]

infoAnfibio/models.py
from django.db import models
import datetime

# Create your models here.
class usuariosAnfibio(models.Model):
    nombre = models.CharField(max_length=64,default='')
    apellido = models.CharField(max_length=64,default='')
    usuario = models.CharField(max_length=64,default='')
    email = models.CharField(max_length=64,default='')
    nroCelular = models.CharField(max_length=64,default='')
    contra = models.CharField(max_length=64,default='')
    codigoUsr = models.CharField(max_length=64,default='OP-0000')
    urlFoto = models.CharField(max_length=512,default='')

class botesAnfibio(models.Model):
    codigoBote = models.CharField(max_length=512,default='')
    urlBote = models.CharField(max_length=512,default='')

class fotosAnfibio(models.Model):
    codigoFoto = models.CharField(max_length=128,default='')
    urlFoto = models.CharField(max_length=512,default='')

class inspecctionInfo(models.Model):
    fechaInspeccion = models.CharField(max_length=128,default='')
    distancia = models.CharField(max_length=128,default='')
    duracion = models.CharField(max_length=128,default='')
    codigoBote = models.CharField(max_length=128,default='')

class inspeccionMultimediaDatos(models.Model):
    fechaInspeccion = models.CharField(max_length=128,default=datetime.datetime.now())
    distancia = models.CharField(max_length=128,default='')
    duracion = models.CharField(max_length=128,default='')
    codigoBote = models.CharField(max_length=128,default='')
    rutaFotos = models.CharField(max_length=128,default='')
    rutaVideo = models.CharField(max_length=128,default='')
    codigoInspeccion = models.CharField(max_length=128,default='')

class fotosInspeccionInformacion(models.Model):
    codigoInspeccion = models.CharField(max_length=128,default='INSP-0000,FOT-0000')
    rutaInspeccion = models.CharField(max_length=128,default='INSP-0000/')
    rutaFoto = models.CharField(max_length=128,default='')
    codigoFoto = models.CharField(max_length=128,default='')

infoAnfibio/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import usuariosAnfibio,botesAnfibio, fotosAnfibio, inspecctionInfo,inspeccionMultimediaDatos
import datetime
import cv2
import os
import serial
import sys
import subprocess as sp

path_fotos_inspeccion = ''
path_videos_inspeccion = ''
video_grabacion = '0'
id_inspeccion = '0'
counter_fotos = '0'
counter_videos = '0'
frames_videos = '0'
app_video = None
#VIDEO_GRABACION es un flag que indica que el video se esta grabando

#captureVideoFoto = cv2.VideoCapture("http://localhost:8080/?action=stream")
#objSerial = serial.Serial('/dev/ttyACM0',115200)

comandosRobot = {'$OAXBTN3':'$OAX1M','$OAXBTN0':'$OAX3J0A','$OAXBTN1':'$OAX3J0B','$OAXBTN2':'$OAX3JB0'}


# Create your views here.
def infoUsuarios(request):
    usuarios_totales = usuariosAnfibio.objects.all()
    usuarios_enviar = []
    for usuario in usuarios_totales:
        usr_datos = [usuario.nombre,usuario.apellido,usuario.codigoUsr,usuario.urlFoto,usuario.usuario]
        usuarios_enviar.append(usr_datos)
    return JsonResponse({
        'usuarios':usuarios_enviar,
    })

def datosUsuario(request):
    usuario_codigo = request.GET.get('codigo')
    print(usuario_codigo)
    usuario_info = usuariosAnfibio.objects.get(codigoUsr=usuario_codigo)
    informacio_usuario = [usuario_info.nombre,usuario_info.apellido,usuario_info.usuario,usuario_info.codigoUsr,usuario_info.urlFoto]
    return JsonResponse({
        'info':informacio_usuario
    })

def crearUsuario(request):
    nombreUsr = request.GET.get('nombre')
    apelllidoUsr = request.GET.get('apellido')
    celularUsr = request.GET.get('celular')
    emailUsr = request.GET.get('email')
    contraUsr = request.GET.get('contra')
    print(nombreUsr)
    print(apelllidoUsr)
    print(celularUsr)
    print(emailUsr)
    print(contraUsr)
    usuariosAnfibio(nombre=nombreUsr,apellido=apelllidoUsr,nroCelular=celularUsr,email=emailUsr,contra=contraUsr).save()
    usr_mod = usuariosAnfibio.objects.get(nombre=nombreUsr)
    usr_mod.usuario = usr_mod.nombre.lower()
    usr_mod.save()
    codUsr = str(usr_mod.id)
    while len(codUsr) < 4:
        codUsr = '0' + codUsr
    usr_mod.codigoUsr = 'OP-' + codUsr
    usr_mod.save()
    return JsonResponse({
        'respuesta':'Ok',
    })

def accederUsuario(request):
    usrCodigo = request.GET.get('codigo')
    usrContra = request.GET.get('contra')
    print(usrCodigo)
    print(usrContra)
    usuario_acceso = usuariosAnfibio.objects.get(codigoUsr=usrCodigo)
    print(usuario_acceso.contra)
    if usrContra == usuario_acceso.contra and usuario_acceso.nombre == 'admin':
        print('Se envia la respuesta del admin')
        return JsonResponse({
            'resp':'300'
        })
    elif usrContra == usuario_acceso.contra:
        return JsonResponse({
            'resp':'200'
        })
    else:
        return JsonResponse({
            'resp':'100'
        })
    
def infoBoats(request):
    botes_totales = botesAnfibio.objects.all()
    botes_enviar = []
    for bote in botes_totales:
        arreglo_bote = [bote.codigoBote,bote.urlBote]
        botes_enviar.append(arreglo_bote)
    return JsonResponse({
        'boats':botes_enviar,
    })

def infoFotos(request):
    fotos_totales = fotosAnfibio.objects.all()
    fotos_enviar = []
    for foto in fotos_totales:
        arreglo_fotos = [foto.id,foto.codigoFoto,foto.urlFoto]
        fotos_enviar.append(arreglo_fotos)
    return JsonResponse({
        'fotos':fotos_enviar,
    })

def consultarEstadisticas(request):
    inspecciones_totales = inspeccionMultimediaDatos.objects.all()
    hora_total = 0.00
    distancia_total = 0.00
    recorridos_totales = 0
    recorridos_totales = len(inspecciones_totales)
    for inspeccion in inspecciones_totales:
        #hora_total = hora_total + round(float(inspeccion.duracion),2)
        hora_total = 25.43
    
    for inspeccion in inspecciones_totales:
        #distancia_total = distancia_total + round(float(inspeccion.distancia),2)
        distancia_total = 54.34
    
    return JsonResponse({
        'horas':str(hora_total),
        'distancia':str(distancia_total),
        'recorridos':str(recorridos_totales)
    })

def infoInspecciones(request):
    inspTotal = inspeccionMultimediaDatos.objects.all().order_by('-id')
    arreglo_enviar = []
    for inspeccion in inspTotal:
        arreglo_insp = [inspeccion.id,inspeccion.fechaInspeccion,inspeccion.distancia,inspeccion.duracion,inspeccion.codigoBote]
        arreglo_enviar.append(arreglo_insp)
    return JsonResponse({
        'inspecciones':arreglo_enviar
    })

def registrarTrabajo(request):
    global id_inspeccion
    duracionTrabajo = request.GET.get('duracion')
    distanciaTrabajo = request.GET.get('distancia')
    fechaRegistro = datetime.datetime.now().strftime('%d-%m-%Y')
    print(duracionTrabajo)
    duracionTrabajo = duracionTrabajo.split(':')
    print(duracionTrabajo)
    duracion = str(round(float(duracionTrabajo[0]) + round(float(duracionTrabajo[1])/60,2),2))
    codigoBote = 'BOT-0001'
    inspeccion_info = inspeccionMultimediaDatos.objects.get(id=id_inspeccion)
    inspeccion_info.distancia = distanciaTrabajo
    inspeccion_info.duracion = duracionTrabajo
    inspeccion_info.codigoBote = codigoBote
    inspeccion_info.save()
    inspecctionInfo(fechaInspeccion=fechaRegistro,distancia=distanciaTrabajo,duracion=duracion,codigoBote=codigoBote).save()
    return JsonResponse({
        'resp':'ok'
    })

#Colocar icono por inspeccion para poder revisar videos y fotos de inspeccion
#Roles de usuario
#Admin
#Adociar videos a inspeccion con botonos y tmb fotos
#Rol de usuario admin, operario
#Acceso de usuario Admin
# --Cerrador
#Iconos de monitoreo (saber si estan prendidos o aplicar funcion
#Guardar los datos finales e iniciales
#Lista de pruebas - App - Integracion con el robot
#Informe Final del software - 18 de Diciembre
#Puntos complementarios Agregar, pantallas, funcionalidades y variables
#Finales
#Tomar Foto - Operador - Tomar FOTO FUNCION

def foto(request,ind):
    fotoVer = fotosAnfibio.objects.get(id=ind)
    return render(request,'infoAnfibio/foto.html',{
        'fotoAnfibio':fotoVer.urlFoto,
    })

#Grabar pocision final e inicial
#Grabar la distancia total recorrida 
#Hacer las pruebas con arduino programado

def capturarFoto(request):
    ret,cv_img = captureVideoFoto.read()
    if ret:
        cv2.imwrite('FOTO_ANFIBIO.png',cv_img)
    return JsonResponse({
        'resp':'200'
    })

def fotosInspeccionTotal(request):
    fuentes_foto = []
    counter = 1
    inspecciones_totales = inspeccionMultimediaDatos.objects.all()
    for inspeccion in inspecciones_totales:
        fotos_inspeccion = os.listdir('infoAnfibio/static/' + inspeccion.rutaFotos)
        print(fotos_inspeccion)
        for foto in fotos_inspeccion:
            fuentes_foto.append([inspeccion.rutaFotos + foto,inspeccion.codigoInspeccion + '-' +foto,f'foto{counter}'])
            counter = counter + 1
    print(fuentes_foto)
    return render(request,'infoAnfibio/Album.html',{
        'fotos_totales':fuentes_foto,
        'tipo':'insp_total'
    })

def videosInpeccionEspecifico(request,ind):
    fuentes_video = []
    inspeccion_info = inspeccionMultimediaDatos.objects.get(id=ind)
    videos_inspeccion = os.listdir('infoAnfibio/static/' + inspeccion_info.rutaVideo)
    for video in videos_inspeccion:
        fuentes_video.append(inspeccion_info.codigoInspeccion + ':' + video)
    return render(request,'infoAnfibio/videoGallery.html',{
        'tipo':'insp_esp',
        'videos_totales':fuentes_video,
        'id_insp':str(ind)
    })

def videosInspeccionTotal(request):
    fuentes_video = []
    inspecciones_totales = inspeccionMultimediaDatos.objects.all()
    for inspeccion in inspecciones_totales:
        videos_inspeccion = os.listdir('infoAnfibio/static/' + inspeccion.rutaVideo)
        for video in videos_inspeccion:
            fuentes_video.append(inspeccion.codigoInspeccion + ':' +video)
    return render(request,'infoAnfibio/videoGallery.html',{
        'videos_totales':fuentes_video,
        'tipo':'insp_total'
    })

def videoPlayer(request,ind):
    print(ind)
    codigoInspeccion = ind.split(':')[0]
    nombreVideo = ind.split(':')[1]
    rutaVideo = inspeccionMultimediaDatos.objects.get(codigoInspeccion=codigoInspeccion).rutaVideo + nombreVideo
    return render(request,'infoAnfibio/videoPlayer.html',{
        'video':str(rutaVideo),
        'tipo':'insp_total',
        'id_insp':str(ind),
    })

def videoEspecifico(request,ind,info):
    codigoInspeccion = ind.split(':')[0]
    nombreVideo = ind.split(':')[1]
    id_insp = info
    rutaVideo = inspeccionMultimediaDatos.objects.get(codigoInspeccion=codigoInspeccion).rutaVideo + nombreVideo
    print(codigoInspeccion)
    print(nombreVideo)
    print(id_insp)
    return render(request,'infoAnfibio/videoPlayer.html',{
        'video':str(rutaVideo),
        'tipo':'insp_esp',
        'id_insp':str(info)
    })

def verVideos(request):
    return render(request,'infoAnfibio/video.html')

def comandoInfo(request):
    comando = request.GET.get('comando')
    #objSerial.write(comandosRobot[comando].encode())
    print(comando)
    return JsonResponse({
        'mensaje':'recibido'
    })

#y = $OAXBTN3
#X = $OAXBTN0

def iniciarInspeccion(request):
    global path_fotos_inspeccion
    global path_videos_inspeccion
    global id_inspeccion
    nueva_insp = 0
    try:
        nueva_insp = 1
        ultima_inspeccion = inspeccionMultimediaDatos.objects.latest('id')
        codigo_identificador = str(int(ultima_inspeccion.id) + 1)
        id_inspeccion = str(int(ultima_inspeccion.id) + 1)
    except:
        nueva_insp = 0
        inspeccionMultimediaDatos().save()
        ult_inspeccion = inspeccionMultimediaDatos.objects.latest('id')
        id_inspeccion = str(ult_inspeccion.id)
        codigo_identificador = str(ult_inspeccion.id)
    #CodigoInspeccion

infoAnfibio/templates/infoAnfibio/Album.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tumi Anfibio</title>
        <base href="./">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'styles/views.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
        <style> @import url("https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"); </style>
    </head>
    <body>
        <div class="app">
            <div class="gallery_view">
                <div class="welcome_header">
                    <img class="welcome_logotumi_img" src="{% static 'Img/tumi_logo_2.png' %}" alt="Logo">
                    <img class="welcome_logotumi_img_2" src="{% static 'Img/separator.png' %}" alt="">
                    <p class="welcome_header_text">Galería</p> 
                </div>
                {% if tipo == 'insp_total' %}
                <a href="http://localhost:3000/Main" style="text-decoration: none">
                    <img class="work_back_img"  src="{% static 'Img/arrow_left.png' %}" alt="">
                </a>
                {% endif %}
                {% if tipo == 'insp_esp' %}
                <a href="http://localhost:3000/MasEstadisticas" style="text-decoration: none">
                    <img class="work_back_img"  src="{% static 'Img/arrow_left.png' %}" alt="">
                </a>
                {% endif %}
                <img class="arrow_img_left"  src="{% static 'Img/arrow_left2.png' %}" alt="" style="visibility: hidden"/>
                <img class="arrow_img_right"  src="{% static 'Img/arrow_right.png' %}" alt=""  style="visibility: hidden"/>
                <div class="gallery_section">
                    {% if tipo == 'insp_total' %}
                        <div class="gallery_container_buttons">
                            <a href="{% url 'infoAnfibio:videosInspeccionTotal' %}" style="text-decoration: none;"><button class="gallery_button button_gallery_enable">Videos</button></a>
                            <a href="{% url 'infoAnfibio:fotosInspeccionTotal' %}" style="text-decoration: none;"><button class="gallery_button button_gallery_disable">Fotos</button></a>
                        </div>
                    {% endif %}
                    {% if tipo == 'insp_esp' %}
                        <div class="gallery_container_buttons">
                            <a href="{% url 'infoAnfibio:videosInspeccionEspecifico' id_insp %}" style="text-decoration: none;"><button class="gallery_button button_gallery_enable">Videos</button></a>
                            <a href="{% url 'infoAnfibio:fotosInspeccionEspecifico' id_insp %}" style="text-decoration: none;"><button class="gallery_button button_gallery_disable">Fotos</button></a>
                        </div>
                    {% endif %}
                    <div class="gallery_boat_row">
                        {%  for foto in fotos_totales %}
                            <div class="gallery_boat">
                                <button style="background-color: transparent; border: solid white 1px; border-radius: 5px;" data-bs-toggle="modal" data-bs-target="#{{ foto.2 }}">
                                    <img src="{% static foto.0 %}" style="display:block; max-width:200px; max-height:200px; width:auto;height:auto;">
                                </button>
                                <h6 style="color: white;">{{ foto.1 }}</h6>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

{% for img in fotos_totales %}
<div class="modal fade" id="{{ img.2 }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="exampleModalLabel">{{ img.1 }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <img class="rounded mx-auto d-block" src="{% static img.0 %}" style="display:block; max-width:720px; max-height:720px; width:auto;height:auto;">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

infoAnfibio/templates/infoAnfibio/foto.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Alexader</title>
    </head>
    <body style="text-align: center;">
        <h1>Fotos Anfibio</h1>
        <img src="{% static fotoAnfibio %}" height="1200px">
        <div>
            <a href="http://localhost:3000/Gallery">Volver</a>    
        </div>    
    </body>
</html>

infoAnfibio/templates/infoAnfibio/videoGallery.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tumi Anfibio</title>
        <base href="./">
        <link rel="stylesheet" type="text/css" href="{% static 'styles/views.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
        <style> @import url("https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"); </style>
    </head>
    <body>
        <div class="app">
            <div class="gallery_view">
                <div class="welcome_header">
                    <img class="welcome_logotumi_img" src="{% static 'Img/tumi_logo_2.png' %}" alt="Logo">
                    <img class="welcome_logotumi_img_2" src="{% static 'Img/separator.png' %}" alt="">
                    <p class="welcome_header_text">Galería</p> 
                </div>
                {% if tipo == 'insp_total' %}
                <a href="http://localhost:3000/Main" style="text-decoration: none">
                    <img class="work_back_img"  src="{% static 'Img/arrow_left.png' %}" alt="">
                </a>
                {% endif %}
                {% if tipo == 'insp_esp' %}
                <a href="http://localhost:3000/MasEstadisticas" style="text-decoration: none">
                    <img class="work_back_img"  src="{% static 'Img/arrow_left.png' %}" alt="">
                </a>
                {% endif %}
                <img class="arrow_img_left"  src="{% static 'Img/arrow_left2.png' %}" alt="" style="visibility: hidden"/>
                <img class="arrow_img_right"  src="{% static 'Img/arrow_right.png' %}" alt=""  style="visibility: hidden"/>
                <div class="gallery_section">
                    {% if tipo == 'insp_total' %}
                        <div class="gallery_container_buttons">
                            <a href="{% url 'infoAnfibio:videosInspeccionTotal' %}" style="text-decoration: none;"><button class="gallery_button button_gallery_disable">Videos</button></a>
                            <a href="{% url 'infoAnfibio:fotosInspeccionTotal' %}" style="text-decoration: none;"><button class="gallery_button button_gallery_enable">Fotos</button></a>
                        </div>
                    {% endif %}
                    {% if tipo == 'insp_esp' %}
                        <div class="gallery_container_buttons">
                            <a href="{% url 'infoAnfibio:videosInspeccionEspecifico' id_insp %}" style="text-decoration: none;"><button class="gallery_button button_gallery_disable">Videos</button></a>
                            <a href="{% url 'infoAnfibio:fotosInspeccionEspecifico' id_insp %}" style="text-decoration: none;"><button class="gallery_button button_gallery_enable">Fotos</button></a>
                        </div>
                    {% endif %}
                    {% if tipo == 'insp_total' %}
                    <div class="gallery_boat_row">
                        {%  for video in videos_totales %}
                            <div class="gallery_boat">
                                <a href="{% url 'infoAnfibio:videoPlayer' video %}"><img src="{% static 'Img/videoPlay.jpg' %}" style="display:block; max-width:200px; max-height:200px; width:auto;height:auto;"></a>
                                <h6 style="color: white;">{{ video }}</h6>
                                <!--<img src="{% static foto %}" style="display:block; max-width:200px; max-height:200px; width:auto;height:auto;">-->
                            </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% if tipo == 'insp_esp' %}
                    <div class="gallery_boat_row">
                        {%  for video in videos_totales %}
                            <div class="gallery_boat">
                                <a href="{% url 'infoAnfibio:videoEspecifico' video id_insp %}"><img src="{% static 'Img/videoPlay.jpg' %}" style="display:block; max-width:200px; max-height:200px; width:auto;height:auto;"></a>
                                <h6 style="color: white;">{{ video }}</h6>
                                <!--<img src="{% static foto %}" style="display:block; max-width:200px; max-height:200px; width:auto;height:auto;">-->
                            </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </body>
</html>